// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFVTKbqRU3iksgcZpTM8XyZTEFblOjGy4',
    appId: '1:749075454262:web:28836fa89680cc0766fb97',
    messagingSenderId: '749075454262',
    projectId: 'ytuo-5253d',
    authDomain: 'ytuo-5253d.firebaseapp.com',
    databaseURL: 'https://ytuo-5253d-default-rtdb.firebaseio.com',
    storageBucket: 'ytuo-5253d.appspot.com',
    measurementId: 'G-1Z13ZVBG7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnkFoutuMDlazntBZuQOYyGa4qi3ZNBCQ',
    appId: '1:749075454262:android:65c06b7397def55c66fb97',
    messagingSenderId: '749075454262',
    projectId: 'ytuo-5253d',
    databaseURL: 'https://ytuo-5253d-default-rtdb.firebaseio.com',
    storageBucket: 'ytuo-5253d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ5o-EWSEOnrZsP5srk0UNZQn4CRujEf4',
    appId: '1:749075454262:ios:32bda6408ff0f4d566fb97',
    messagingSenderId: '749075454262',
    projectId: 'ytuo-5253d',
    databaseURL: 'https://ytuo-5253d-default-rtdb.firebaseio.com',
    storageBucket: 'ytuo-5253d.appspot.com',
    iosBundleId: 'com.ytuo.ytuOri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ5o-EWSEOnrZsP5srk0UNZQn4CRujEf4',
    appId: '1:749075454262:ios:32bda6408ff0f4d566fb97',
    messagingSenderId: '749075454262',
    projectId: 'ytuo-5253d',
    databaseURL: 'https://ytuo-5253d-default-rtdb.firebaseio.com',
    storageBucket: 'ytuo-5253d.appspot.com',
    iosBundleId: 'com.ytuo.ytuOri',
  );
}
